# Nama package kita
package_name: regression_model

# File dataset kita
training_data_file: train.csv
test_data_file: test.csv

# Variables
# Variabel dependen yang ingin kita prediksi
target: SalePrice

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

# Kita akan merubah nama 3 variabel ini agar tidak error (karena dimulai dengan angka)
variables_to_rename:
  1stFlrSF: FirstFlrSF
  2ndFlrSF: SecondFlrSF
  3SsnPorch: ThreeSsnPortch

features:
  - MSSubClass
  - MSZoning
  - LotFrontage
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - OverallQual
  - OverallCond
  - YearRemodAdd
  - RoofStyle
  - Exterior1st
  - ExterQual
  - Foundation
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - HeatingQC
  - CentralAir
  - FirstFlrSF  # ganti nama
  - SecondFlrSF  # ganti nama
  - GrLivArea
  - BsmtFullBath
  - HalfBath
  - KitchenQual
  - TotRmsAbvGrd
  - Functional
  - Fireplaces
  - FireplaceQu
  - GarageFinish
  - GarageCars
  - GarageArea
  - PavedDrive
  - WoodDeckSF
  - ScreenPorch
  - SaleCondition
  # Ini untuk meghitung variabel yg berhubungan dengan waktu:
  - YrSold

# Ukuran train-test split
test_size: 0.1

# menentukan random seed
random_state: 0

alpha: 0.001

# Variabel kategori dengan nilai NA di training set 
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

categorical_vars_with_na_missing:
  - FireplaceQu

numerical_vars_with_na:
  - LotFrontage

temporal_vars:
  - YearRemodAdd

ref_var: YrSold


# Variabel yang akan dilakukan logtransform
numericals_log_vars:
  - LotFrontage
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# Variabel untuk proses mapping
qual_vars:
  - ExterQual
  - BsmtQual
  - HeatingQC
  - KitchenQual
  - FireplaceQu

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - MSSubClass
  - MSZoning
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - RoofStyle
  - Exterior1st
  - Foundation
  - CentralAir
  - Functional
  - PavedDrive
  - SaleCondition

# variable mappings
qual_mappings:
  Po: 1
  Fa: 2
  TA: 3
  Gd: 4
  Ex: 5
  Missing: 0
  NA: 0

exposure_mappings:
  No: 1
  Mn: 2
  Av: 3
  Gd: 4


finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6


garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3
