[tool.poetry]
name = "osin"
version = "0.1.6"
description = "Rethink Experimenting"
authors = ["Binh Vu <binh@toan2.com>"]
homepage = "https://github.com/binh-vu/osin"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
pandas = "^1.2.4"
streamlit = "^0.82.0"
python-dotenv = "^0.17.1"
peewee = "^3.14.4"
"ruamel.yaml" = "^0.17.9"
loguru = "^0.5.3"
matplotlib = "^3.4.2"
seaborn = "^0.11.1"
plotly = "^5.0.0"
streamlit-callbacks = "^0.0.5"
tornado = "^6.1"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
