[tool.poetry]
name = "kaigara"
version = "0.0.1a8"
description = ""
license = "ISC"
authors = ["Noshita, Koji <noshita@morphometrics.jp>"]
homepage = ""
repository = "https://github.com/noshita/kaigara"
readme = "README.md"
keywords = ["theoretical morphology", "malacology"]
classifiers = [
	'Intended Audience :: Science/Research',
	'Intended Audience :: Developers',
	'License :: OSI Approved :: ISC License (ISCL)',
	'Programming Language :: Python',
	'Topic :: Software Development',
	'Topic :: Scientific/Engineering',
	'Operating System :: Microsoft :: Windows',
	'Operating System :: POSIX',
	'Operating System :: Unix',
	'Operating System :: MacOS',
	'Programming Language :: Python :: 3.7',
	'Programming Language :: Python :: 3.8',
	'Programming Language :: Python :: 3.9'
	]

[tool.poetry.dependencies]
python = ">=3.7.10,<4.0"
kiwisolver = "^1.3.1"
numpy = "^1.21.0"
scipy = "^1.6.1"
sympy = "^1.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
jupyter = "^1.0.0"
jupyterlab = "^3.0"
matplotlib = "^3.4"
plotly = "^4.14"
scikit-learn = "^0.24"
jedi = "^0.18"
poetry2conda = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "kaigara"